from tkinter import *
table=Tk()
table.geometry("1100x600")
table.title("student information storing file")
table.resizable(False,False)
l1=Label(table,text="Enter the first name",font=("calibri",18,"bold"))
l1.grid(row=0,column=0)
e1=Entry(table,font=("calibri",18,"bold"))
e1.grid(row=0,column=1)
l2=Label(table,text="Enter the last name",font=("calibri",18,"bold"))
l2.grid(row=0,column=2)
e2=Entry(table,font=("calibri",18,"bold"))
e2.grid(row=0,column=3)
l3=Label(table,text="Enter the class",font=("calibri",18,"bold"))
l3.grid(row=1,column=0)
e3=Entry(table,font=("calibri",18,"bold"))
e3.grid(row=1,column=1)
l4=Label(table,text="Enter the class division",font=("calibri",18,"bold"))
l4.grid(row=1,column=2)
e4=Entry(table,font=("calibri",18,"bold"))
e4.grid(row=1,column=3)
l11=Label(table,text="Enter the roll number",font=("calibri",18,"bold"))
l11.grid(row=2,column=0)
e11=Entry(table,font=("calibri",18,"bold"))
e11.grid(row=2,column=1)
l12=Label(table,text="Enter the id number",font=("calibri",18,"bold"))
l12.grid(row=2,column=2)
e12=Entry(table,font=("calibri",18,"bold"))
e12.grid(row=2,column=3)
l5=Label(table,text="Enter the marks of english",font=("calibri",18,"bold"))
l5.grid(row=3,column=0)
e5=Entry(table,font=("calibri",18,"bold"))
e5.grid(row=3,column=1)
l6=Label(table,text="Enter the marks of urdu",font=("calibri",18,"bold"))
l6.grid(row=3,column=2)
e6=Entry(table,font=("calibri",18,"bold"))
e6.grid(row=3,column=3)
l7=Label(table,text="Enter the marks of maths",font=("calibri",18,"bold"))
l7.grid(row=4,column=0)
e7=Entry(table,font=("calibri",18,"bold"))
e7.grid(row=4,column=1)
l8=Label(table,text="Enter the marks of science",font=("calibri",18,"bold"))
l8.grid(row=4,column=2)
e8=Entry(table,font=("calibri",18,"bold"))
e8.grid(row=4,column=3)
l9=Button(table,text="Store Data",padx=20,font=("calibri",22,"bold"))
l9.grid(row=5,column=1)
table.mainloop()