from tkinter import *

def save_data():
    print("Button is Clicked!")
    print(fname.get())
    print(lname.get())
    print(sclass.get())
    print(division.get())
    print(rnumber.get())
    print(idnumber.get())
    print(english.get())
    print(urdu.get())
    print(maths.get())
    print(science.get())

table=Tk()
table.title("student information storing file")
table.resizable(False,False)
fname=StringVar()
lname=StringVar()
sclass=StringVar()
division=StringVar()
rnumber=StringVar()
idnumber=StringVar()
english=StringVar()
urdu=StringVar()
maths=StringVar()
science=StringVar()
l1=Label(table,text="Enter the first name",font=("calibri",18,"bold"),padx=10,pady=10)
l1.grid(row=0,column=0,padx=10,pady=10)
e1=Entry(table,font=("calibri",18,"bold"),textvariable=fname)
e1.grid(row=0,column=1,padx=10,pady=10)
l2=Label(table,text="Enter the last name",font=("calibri",18,"bold"),padx=10,pady=10)
l2.grid(row=0,column=2,padx=10,pady=10)
e2=Entry(table,font=("calibri",18,"bold"),textvariable=lname)
e2.grid(row=0,column=3,padx=10,pady=10)
l3=Label(table,text="Enter the class",font=("calibri",18,"bold"),padx=10,pady=10)
l3.grid(row=1,column=0,padx=10,pady=10)
e3=Entry(table,font=("calibri",18,"bold"),textvariable=sclass)
e3.grid(row=1,column=1,padx=10,pady=10)
l4=Label(table,text="Enter the class division",font=("calibri",18,"bold"),padx=10,pady=10)
l4.grid(row=1,column=2,padx=10,pady=10)
e4=Entry(table,font=("calibri",18,"bold"),textvariable=division)
e4.grid(row=1,column=3,padx=10,pady=10)
l11=Label(table,text="Enter the roll number",font=("calibri",18,"bold"),padx=10,pady=10)
l11.grid(row=2,column=0,padx=10,pady=10)
e11=Entry(table,font=("calibri",18,"bold"),textvariable=rnumber)
e11.grid(row=2,column=1,padx=10,pady=10)
l10=Label(table,text="Enter the student id number",font=("calibri",18,"bold"),padx=10,pady=10)
l10.grid(row=2,column=2,padx=10,pady=10)
e10=Entry(table,font=("calibri",18,"bold"),textvariable=idnumber)
e10.grid(row=2,column=3,padx=10,pady=10)
l5=Label(table,text="Enter the marks of english",font=("calibri",18,"bold"),padx=10,pady=10)
l5.grid(row=3,column=0,padx=10,pady=10)
e5=Entry(table,font=("calibri",18,"bold"),textvariable=english)
e5.grid(row=3,column=1,padx=10,pady=10)
l6=Label(table,text="Enter the marks of urdu",font=("calibri",18,"bold"),padx=10,pady=10)
l6.grid(row=3,column=2,padx=10,pady=10)
e6=Entry(table,font=("calibri",18,"bold"),textvariable=urdu)
e6.grid(row=3,column=3,padx=10,pady=10)
l7=Label(table,text="Enter the marks of maths",font=("calibri",18,"bold"),padx=10,pady=10)
l7.grid(row=4,column=0,padx=10,pady=10)
e7=Entry(table,font=("calibri",18,"bold"),textvariable=maths)
e7.grid(row=4,column=1,padx=10,pady=10)
l8=Label(table,text="Enter the marks of science",font=("calibri",18,"bold"),padx=10,pady=10)
l8.grid(row=4,column=2,padx=10,pady=10)
e8=Entry(table,font=("calibri",18,"bold"),textvariable=science)
e8.grid(row=4,column=3,padx=10,pady=10)
l9=Button(table,text="Store Data",padx=20,font=("calibri",22,"bold"),command=save_data)
l9.grid(row=5,column=1,padx=10,pady=10)
table.mainloop()